export interface Site {
  siteId: string | number;
  siteName?: string;
  siteStatus?: string;
  locationId?: string | number;
  deviceId?: string | number;
  deviceName?: string;
  deviceCode?: string;
  deviceStatus?: string;
  deviceInstallationDate?: string;
  siteCode?: string;
  regionId?: number;
  regionName?: string;
  subRegionId?: number;
  subRegionName?: string;
  zoneId?: number;
  zoneName?: string;
  name: string;
  status: 'online' | 'offline' | 'warning' | 'active' | string;
  code?: string;
  address?: string;
  coordinates?: string;
  mqttHost?: string;
  mqttPort?: number;
  mqttClientId?: string;
  useTls?: boolean;
  keepAliveSeconds?: number;
  rmsSubscribeTopic?: string;
  aiSubscribeTopic?: string;
  type: string;
  location: string;
  battery: string;
  lastSeen: string;
}
